### ISSUE TITLE
Integrating Spring Cloud Config with a Spring Boot Client

### ISSUE THREAD

**Issue by zikozee** [zikozee/spring-microservices-in-action#5]
- config server to license service 

- configuring the license service to use Spring Cloud Config
  - Usually, the information you store in the **application.yml** is configuration data that you might  want to have available to a service even if the Spring Cloud Config service is unavailable
```yaml
spring:
  application:
    name: licensing-service  # this name is used bySpring Cloud config Client to know which service is being looked up in the config server
  
  profiles:
    active: dev       # specifies the default profile to run
    
  cloud:
    config:
      uri: http://localhost:8071  # specifies the location of the Spring Cloud Config server
```
